import type { LucideIcon } from "lucide-react";
import {
  Combine,
  Scissors,
  LayoutGrid,
  RotateCw,
  FileOutput,
  Trash2,
  Minimize2,
  Wrench,
  Image as ImageIcon,
  FileImage,
  Images,
  FileType,
  FileText,
  FileSpreadsheet,
  Presentation,
  Code2,
  Pencil,
  Highlighter,
  Crop,
  Droplets,
  Hash,
  PanelTop,
  EyeOff,
  Lock,
  Unlock,
  Layers,
  PenTool,
  FormInput,
  ScanText,
  Sparkles,
  Grid2x2,
  BookOpen,
  ArrowDownUp,
  Eraser,
  Copy,
  FilePlus,
  SplitSquareVertical,
  Bookmark,
  GitCompare,
  Contrast,
  Aperture,
  Gauge,
  Binary,
  Type,
  FileCode,
  FileDown,
  Presentation as PptIcon,
  BookMarked,
  FileInput,
  Table,
  Smartphone,
  QrCode,
  Barcode,
  Stamp,
  Layers2,
  FlipVertical2,
  Scan,
  MessageSquare,
  Languages,
  ShieldCheck,
  BadgeCheck,
  SprayCan,
  Info,
  Paperclip,
  Mail,
  Baseline,
  Calendar,
  BookOpenCheck,
  Calculator,
  LayoutTemplate,
  CreditCard,
  Replace,
  Palette,
  Ban,
  ImageDown,
  FileSearch,
  FolderKanban,
} from "lucide-react";

export type ToolCategory =
  | "organize"
  | "optimize"
  | "convert"
  | "edit"
  | "security"
  | "sign"
  | "ai"
  | "view"
  | "batch";

export interface ToolDef {
  slug: string;
  href: string;
  name: string;
  short: string;
  description: string;
  category: ToolCategory;
  icon: LucideIcon;
  featured?: boolean;
  accept?: string;
  multiple?: boolean;
  status?: "full" | "partial";
}

export const CATEGORY_LABELS: Record<ToolCategory, string> = {
  organize: "Organize",
  optimize: "Optimize",
  convert: "Convert",
  edit: "Edit & Annotate",
  security: "Security",
  sign: "Sign & Forms",
  ai: "AI / Smart",
  view: "View & Utility",
  batch: "Batch",
};

export const CATEGORY_ORDER: ToolCategory[] = [
  "organize",
  "optimize",
  "convert",
  "edit",
  "security",
  "sign",
  "ai",
  "view",
  "batch",
];

export const TOOLS: ToolDef[] = [
  // —— Organize (existing) ——
  {
    slug: "merge",
    href: "/merge",
    name: "Merge PDF",
    short: "Combine PDFs",
    description: "Merge multiple PDF files into one. Reorder freely before combining.",
    category: "organize",
    icon: Combine,
    featured: true,
    accept: "application/pdf",
    multiple: true,
  },
  {
    slug: "split",
    href: "/split",
    name: "Split PDF",
    short: "Extract or split",
    description: "Split by page ranges or save every page as its own PDF.",
    category: "organize",
    icon: Scissors,
    featured: true,
    accept: "application/pdf",
  },
  {
    slug: "organize",
    href: "/organize",
    name: "Organize pages",
    short: "Reorder & rotate",
    description: "Visually reorder, rotate, or delete pages in your PDF.",
    category: "organize",
    icon: LayoutGrid,
    featured: true,
    accept: "application/pdf",
  },
  {
    slug: "rotate",
    href: "/rotate",
    name: "Rotate PDF",
    short: "Rotate pages",
    description: "Rotate all pages or selected pages by 90°, 180°, or 270°.",
    category: "organize",
    icon: RotateCw,
    accept: "application/pdf",
  },
  {
    slug: "extract",
    href: "/extract",
    name: "Extract pages",
    short: "Pick pages",
    description: "Select pages and export them as a new PDF.",
    category: "organize",
    icon: FileOutput,
    accept: "application/pdf",
  },
  {
    slug: "delete-pages",
    href: "/delete-pages",
    name: "Delete pages",
    short: "Remove pages",
    description: "Remove selected pages from your PDF.",
    category: "organize",
    icon: Trash2,
    accept: "application/pdf",
  },
  {
    slug: "n-up",
    href: "/n-up",
    name: "N-up PDF",
    short: "2/4/6/9 per sheet",
    description: "Impose 2, 4, 6, or 9 pages onto each sheet for handouts or proofing.",
    category: "organize",
    icon: Grid2x2,
    accept: "application/pdf",
  },
  {
    slug: "booklet",
    href: "/booklet",
    name: "Booklet",
    short: "Fold imposition",
    description: "Reorder pages for saddle-stitch booklet printing (fold & staple).",
    category: "organize",
    icon: BookOpen,
    accept: "application/pdf",
  },
  {
    slug: "reverse-pages",
    href: "/reverse-pages",
    name: "Reverse pages",
    short: "Flip order",
    description: "Reverse the page order of your PDF in one click.",
    category: "organize",
    icon: ArrowDownUp,
    accept: "application/pdf",
  },
  {
    slug: "remove-blank-pages",
    href: "/remove-blank-pages",
    name: "Remove blank pages",
    short: "Detect empties",
    description: "Render pages and drop near-empty ones — great after scans.",
    category: "organize",
    icon: Eraser,
    accept: "application/pdf",
  },
  {
    slug: "duplicate-pages",
    href: "/duplicate-pages",
    name: "Duplicate pages",
    short: "Copy pages",
    description: "Duplicate selected pages and append copies to the PDF.",
    category: "organize",
    icon: Copy,
    accept: "application/pdf",
  },
  {
    slug: "add-blank-pages",
    href: "/add-blank-pages",
    name: "Add blank pages",
    short: "Insert blanks",
    description: "Insert blank pages at the start, end, or after a given page.",
    category: "organize",
    icon: FilePlus,
    accept: "application/pdf",
  },
  {
    slug: "split-by-size",
    href: "/split-by-size",
    name: "Split by size",
    short: "Max file size",
    description: "Split a PDF into parts under a target byte size (email limits).",
    category: "organize",
    icon: SplitSquareVertical,
    accept: "application/pdf",
  },
  {
    slug: "split-by-bookmarks",
    href: "/split-by-bookmarks",
    name: "Split by bookmarks",
    short: "Outline sections",
    description: "Split on PDF bookmarks when present; otherwise every N pages.",
    category: "organize",
    icon: Bookmark,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "compare",
    href: "/compare",
    name: "Compare PDFs",
    short: "Text + image diff",
    description: "Side-by-side text similarity and page-1 image difference %.",
    category: "organize",
    icon: GitCompare,
    accept: "application/pdf",
    multiple: true,
  },
  {
    slug: "poster",
    href: "/poster",
    name: "Poster / tile",
    short: "Large print tiles",
    description: "Tile page 1 across a grid of sheets for wall posters.",
    category: "organize",
    icon: LayoutTemplate,
    accept: "application/pdf",
  },
  {
    slug: "business-card",
    href: "/business-card",
    name: "Business card sheet",
    short: "Multi-up cards",
    description: "Tile a card image onto an A4 sheet for print & cut.",
    category: "organize",
    icon: CreditCard,
    accept: "image/*,.jpg,.jpeg,.png,.webp",
  },

  // —— Optimize ——
  {
    slug: "compress",
    href: "/compress",
    name: "Compress PDF",
    short: "Reduce size",
    description: "Shrink PDF size by downsampling embedded images. Honest about limits.",
    category: "optimize",
    icon: Minimize2,
    featured: true,
    accept: "application/pdf",
  },
  {
    slug: "repair",
    href: "/repair",
    name: "Repair PDF",
    short: "Re-save & fix",
    description: "Best-effort repair by re-writing the PDF structure with pdf-lib.",
    category: "optimize",
    icon: Wrench,
    accept: "application/pdf",
  },
  {
    slug: "grayscale",
    href: "/grayscale",
    name: "Grayscale PDF",
    short: "B&W pages",
    description: "Convert pages to grayscale via canvas re-embed — print prep.",
    category: "optimize",
    icon: Contrast,
    accept: "application/pdf",
  },
  {
    slug: "invert",
    href: "/invert",
    name: "Invert colors",
    short: "High-contrast",
    description: "Invert page colors for high-contrast print or night reading prep.",
    category: "optimize",
    icon: Aperture,
    accept: "application/pdf",
  },
  {
    slug: "dpi-resample",
    href: "/dpi-resample",
    name: "DPI resample",
    short: "72–300 DPI",
    description: "Re-render pages at a target DPI with stronger compress presets.",
    category: "optimize",
    icon: Gauge,
    accept: "application/pdf",
  },
  {
    slug: "linearize",
    href: "/linearize",
    name: "Optimize structure",
    short: "Rewrite PDF",
    description: "Best-effort object-stream rewrite (not Acrobat Fast Web View).",
    category: "optimize",
    icon: Binary,
    accept: "application/pdf",
    status: "partial",
  },

  // —— Convert ——
  {
    slug: "jpg-to-pdf",
    href: "/jpg-to-pdf",
    name: "JPG to PDF",
    short: "Images → PDF",
    description: "Convert JPG photos into a polished multi-page PDF.",
    category: "convert",
    icon: ImageIcon,
    featured: true,
    accept: "image/jpeg,.jpg,.jpeg",
    multiple: true,
  },
  {
    slug: "png-to-pdf",
    href: "/png-to-pdf",
    name: "PNG to PDF",
    short: "PNG → PDF",
    description: "Convert PNG images into a PDF document.",
    category: "convert",
    icon: FileImage,
    accept: "image/png,.png",
    multiple: true,
  },
  {
    slug: "images-to-pdf",
    href: "/images-to-pdf",
    name: "Images to PDF",
    short: "Any images",
    description: "Drop JPG, PNG, or WebP images and build a PDF.",
    category: "convert",
    icon: Images,
    accept: "image/*,.jpg,.jpeg,.png,.webp",
    multiple: true,
  },
  {
    slug: "pdf-to-jpg",
    href: "/pdf-to-jpg",
    name: "PDF to JPG",
    short: "Pages → JPG",
    description: "Render each PDF page to a high-quality JPG (ZIP if many).",
    category: "convert",
    icon: FileType,
    featured: true,
    accept: "application/pdf",
  },
  {
    slug: "pdf-to-png",
    href: "/pdf-to-png",
    name: "PDF to PNG",
    short: "Pages → PNG",
    description: "Render each PDF page to a PNG image (ZIP if many).",
    category: "convert",
    icon: FileImage,
    accept: "application/pdf",
  },
  {
    slug: "word-to-pdf",
    href: "/word-to-pdf",
    name: "Word to PDF",
    short: "DOCX → PDF",
    description: "Free local: convert .docx to PDF via HTML rendering in your browser.",
    category: "convert",
    icon: FileText,
    accept: ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    status: "partial",
  },
  {
    slug: "pdf-to-word",
    href: "/pdf-to-word",
    name: "PDF to Word",
    short: "Text extract",
    description: "Free local approximation: export PDF text to Word-friendly HTML/DOC.",
    category: "convert",
    icon: FileText,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "excel-to-pdf",
    href: "/excel-to-pdf",
    name: "Excel to PDF",
    short: "XLSX → PDF",
    description: "Free local: convert spreadsheet sheets into a printable PDF.",
    category: "convert",
    icon: FileSpreadsheet,
    accept: ".xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    status: "partial",
  },
  {
    slug: "pdf-to-excel",
    href: "/pdf-to-excel",
    name: "PDF to Excel",
    short: "Tables → XLSX",
    description: "Free local best-effort table/text extraction into a spreadsheet.",
    category: "convert",
    icon: FileSpreadsheet,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "ppt-to-pdf",
    href: "/ppt-to-pdf",
    name: "PPT to PDF",
    short: "Slides → PDF",
    description: "Free local approximation — convert PowerPoint when possible.",
    category: "convert",
    icon: Presentation,
    accept: ".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation",
    status: "partial",
  },
  {
    slug: "html-to-pdf",
    href: "/html-to-pdf",
    name: "HTML to PDF",
    short: "Paste HTML",
    description: "Turn pasted HTML into a PDF using browser print rendering.",
    category: "convert",
    icon: Code2,
  },
  {
    slug: "pdf-to-text",
    href: "/pdf-to-text",
    name: "PDF to text",
    short: "Plain text",
    description: "Extract plain text from every page — copy or download .txt.",
    category: "convert",
    icon: Type,
    accept: "application/pdf",
    featured: true,
  },
  {
    slug: "pdf-to-html",
    href: "/pdf-to-html",
    name: "PDF to HTML",
    short: "Positioned text",
    description: "Free local approx: positioned text spans from pdf.js textContent.",
    category: "convert",
    icon: FileCode,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "pdf-to-markdown",
    href: "/pdf-to-markdown",
    name: "PDF to Markdown",
    short: "MD export",
    description: "Export page text as Markdown headings + paragraphs.",
    category: "convert",
    icon: FileDown,
    accept: "application/pdf",
  },
  {
    slug: "pdf-to-pptx",
    href: "/pdf-to-pptx",
    name: "PDF to PowerPoint",
    short: "Image slides",
    description: "Creative free path: each page becomes an image slide in a PPTX.",
    category: "convert",
    icon: PptIcon,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "pdf-to-epub",
    href: "/pdf-to-epub",
    name: "PDF to EPUB",
    short: "Text ebook",
    description: "Creative free path: text chapters → EPUB skeleton (JSZip).",
    category: "convert",
    icon: BookMarked,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "markdown-to-pdf",
    href: "/markdown-to-pdf",
    name: "Markdown to PDF",
    short: "MD → PDF",
    description: "Paste Markdown and get a printable PDF (local, best-effort).",
    category: "convert",
    icon: FileInput,
  },
  {
    slug: "txt-to-pdf",
    href: "/txt-to-pdf",
    name: "TXT to PDF",
    short: "Plain → PDF",
    description: "Turn a .txt file or pasted text into a multi-page PDF.",
    category: "convert",
    icon: FileText,
    accept: "text/plain,.txt",
  },
  {
    slug: "csv-to-pdf",
    href: "/csv-to-pdf",
    name: "CSV to PDF",
    short: "Table print",
    description: "Render a CSV as a simple printable table PDF.",
    category: "convert",
    icon: Table,
    accept: "text/csv,.csv",
  },
  {
    slug: "heic-to-pdf",
    href: "/heic-to-pdf",
    name: "HEIC to PDF",
    short: "iPhone photos",
    description: "Convert HEIC/HEIF photos to PDF in-browser via heic2any.",
    category: "convert",
    icon: Smartphone,
    accept: "image/heic,image/heif,.heic,.heif",
    multiple: true,
    status: "partial",
  },
  {
    slug: "webp-to-pdf",
    href: "/webp-to-pdf",
    name: "WebP to PDF",
    short: "WebP → PDF",
    description: "Convert WebP images into a PDF document.",
    category: "convert",
    icon: ImageIcon,
    accept: "image/webp,.webp",
    multiple: true,
  },
  {
    slug: "svg-to-pdf",
    href: "/svg-to-pdf",
    name: "SVG to PDF",
    short: "Vector → PDF",
    description: "Rasterize an SVG in-canvas and embed as a PDF page.",
    category: "convert",
    icon: Palette,
    accept: "image/svg+xml,.svg",
  },

  // —— Edit ——
  {
    slug: "edit",
    href: "/edit",
    name: "Edit PDF",
    short: "Full editor",
    description: "Annotate, rearrange, sign, fill forms, search, and export — the flagship editor.",
    category: "edit",
    icon: Pencil,
    featured: true,
    accept: "application/pdf",
  },
  {
    slug: "annotate",
    href: "/annotate",
    name: "Annotate PDF",
    short: "Markup",
    description: "Highlight, underline, draw, and note — opens the full editor.",
    category: "edit",
    icon: Highlighter,
    accept: "application/pdf",
  },
  {
    slug: "crop",
    href: "/crop",
    name: "Crop PDF",
    short: "Crop pages",
    description: "Crop page margins uniformly or per-page.",
    category: "edit",
    icon: Crop,
    accept: "application/pdf",
  },
  {
    slug: "watermark",
    href: "/watermark",
    name: "Watermark",
    short: "Stamp pages",
    description: "Add text or image watermarks with opacity and position controls.",
    category: "edit",
    icon: Droplets,
    featured: true,
    accept: "application/pdf",
  },
  {
    slug: "page-numbers",
    href: "/page-numbers",
    name: "Page numbers",
    short: "Number pages",
    description: "Add page numbers to headers or footers.",
    category: "edit",
    icon: Hash,
    accept: "application/pdf",
  },
  {
    slug: "header-footer",
    href: "/header-footer",
    name: "Header & footer",
    short: "Custom text",
    description: "Add custom header and footer text across pages.",
    category: "edit",
    icon: PanelTop,
    accept: "application/pdf",
  },
  {
    slug: "redact",
    href: "/redact",
    name: "Redact PDF",
    short: "Black-box",
    description: "Cover sensitive regions with black boxes and flatten.",
    category: "edit",
    icon: EyeOff,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "bates-number",
    href: "/bates-number",
    name: "Bates numbering",
    short: "Prefix + counter",
    description: "Stamp sequential Bates numbers with a custom prefix.",
    category: "edit",
    icon: Stamp,
    accept: "application/pdf",
  },
  {
    slug: "background",
    href: "/background",
    name: "Background",
    short: "Color or image",
    description: "Place a color or image behind page content.",
    category: "edit",
    icon: Layers2,
    accept: "application/pdf",
  },
  {
    slug: "overlay-pdf",
    href: "/overlay-pdf",
    name: "Overlay PDF",
    short: "Stamp on top",
    description: "Stamp page 1 of one PDF onto pages of another.",
    category: "edit",
    icon: FlipVertical2,
    accept: "application/pdf",
    multiple: true,
  },
  {
    slug: "underlay-pdf",
    href: "/underlay-pdf",
    name: "Underlay PDF",
    short: "Stamp behind",
    description: "Place another PDF behind your pages as a letterhead/underlay.",
    category: "edit",
    icon: Layers,
    accept: "application/pdf",
    multiple: true,
  },
  {
    slug: "qr-stamp",
    href: "/qr-stamp",
    name: "QR stamp",
    short: "Add QR code",
    description: "Stamp a QR code (url, text, email) onto every page.",
    category: "edit",
    icon: QrCode,
    accept: "application/pdf",
  },
  {
    slug: "barcode",
    href: "/barcode",
    name: "Barcode stamp",
    short: "Code128 visual",
    description: "Stamp a free visual Code128-style barcode on pages.",
    category: "edit",
    icon: Barcode,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "scan-enhance",
    href: "/scan-enhance",
    name: "Scan enhance",
    short: "Contrast / OCR prep",
    description: "Boost contrast or threshold scans for cleaner OCR prep.",
    category: "edit",
    icon: Scan,
    accept: "application/pdf",
  },
  {
    slug: "deskew",
    href: "/deskew",
    name: "Deskew / straighten",
    short: "Scan straighten",
    description: "Creative free path: contrast + enhance skewed scans (approx).",
    category: "edit",
    icon: RotateCw,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "remove-annotations",
    href: "/remove-annotations",
    name: "Remove annotations",
    short: "Strip markup",
    description: "Best-effort strip of Annots and form fields with pdf-lib.",
    category: "edit",
    icon: Ban,
    accept: "application/pdf",
  },
  {
    slug: "extract-images",
    href: "/extract-images",
    name: "Extract images",
    short: "Pages as images",
    description: "Export page renders (and best-effort embeds) as a ZIP of PNGs.",
    category: "edit",
    icon: ImageDown,
    accept: "application/pdf",
  },
  {
    slug: "replace-text",
    href: "/replace-text",
    name: "Replace text",
    short: "Overlay replace",
    description: "Free local approx: find text via pdf.js, cover with white + redraw.",
    category: "edit",
    icon: Replace,
    accept: "application/pdf",
    status: "partial",
  },

  // —— Security ——
  {
    slug: "protect",
    href: "/protect",
    name: "Protect PDF",
    short: "Add password",
    description: "Encrypt your PDF with a password (user permissions).",
    category: "security",
    icon: Lock,
    featured: true,
    accept: "application/pdf",
  },
  {
    slug: "unlock",
    href: "/unlock",
    name: "Unlock PDF",
    short: "Remove password",
    description: "Decrypt a password-protected PDF when you know the password.",
    category: "security",
    icon: Unlock,
    accept: "application/pdf",
  },
  {
    slug: "flatten",
    href: "/flatten",
    name: "Flatten PDF",
    short: "Flatten forms",
    description: "Flatten form fields and annotations into page content.",
    category: "security",
    icon: Layers,
    accept: "application/pdf",
  },
  {
    slug: "restrict-permissions",
    href: "/restrict-permissions",
    name: "Restrict permissions",
    short: "Owner password",
    description: "Best-effort owner-password encrypt (pdf-lib limits apply).",
    category: "security",
    icon: ShieldCheck,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "certificate-seal",
    href: "/certificate-seal",
    name: "Visual seal",
    short: "Not real PKI",
    description: "Honest visual certificate seal — not cryptographic PKI signing.",
    category: "security",
    icon: BadgeCheck,
    accept: "application/pdf",
  },
  {
    slug: "sanitize",
    href: "/sanitize",
    name: "Sanitize PDF",
    short: "Strip metadata/JS",
    description: "Remove metadata, JS hooks, and annotations best-effort.",
    category: "security",
    icon: SprayCan,
    accept: "application/pdf",
  },
  {
    slug: "metadata",
    href: "/metadata",
    name: "PDF metadata",
    short: "View & edit",
    description: "View and edit title, author, subject, and keywords.",
    category: "security",
    icon: Info,
    accept: "application/pdf",
  },
  {
    slug: "attach-files",
    href: "/attach-files",
    name: "Attach files",
    short: "Embed attachments",
    description: "Attach files inside a PDF (pdf-lib embedded files).",
    category: "security",
    icon: Paperclip,
    accept: "application/pdf",
  },
  {
    slug: "extract-attachments",
    href: "/extract-attachments",
    name: "Extract attachments",
    short: "List embeds",
    description: "Best-effort list/extract of embedded file names from a PDF.",
    category: "security",
    icon: FileOutput,
    accept: "application/pdf",
    status: "partial",
  },

  // —— Sign ——
  {
    slug: "sign",
    href: "/sign",
    name: "Sign PDF",
    short: "Add signature",
    description: "Draw, type, or upload a signature and place it on your PDF.",
    category: "sign",
    icon: PenTool,
    featured: true,
    accept: "application/pdf",
  },
  {
    slug: "fill-form",
    href: "/fill-form",
    name: "Fill PDF form",
    short: "AcroForms",
    description: "Fill interactive AcroForm fields and download the result.",
    category: "sign",
    icon: FormInput,
    accept: "application/pdf",
  },
  {
    slug: "request-sign",
    href: "/request-sign",
    name: "Request signature",
    short: "Free pack + mailto",
    description: "Generate a free signature-request pack (PDF + JSON + mailto) — no DocuSign fees.",
    category: "sign",
    icon: Mail,
    accept: "application/pdf",
  },
  {
    slug: "initials",
    href: "/initials",
    name: "Initials",
    short: "Stamp initials",
    description: "Stamp your initials on the last page (or chosen page).",
    category: "sign",
    icon: Baseline,
    accept: "application/pdf",
  },
  {
    slug: "date-stamp",
    href: "/date-stamp",
    name: "Date stamp",
    short: "Stamp a date",
    description: "Add today's date (or a custom string) to every page.",
    category: "sign",
    icon: Calendar,
    accept: "application/pdf",
  },

  // —— AI ——
  {
    slug: "ocr",
    href: "/ocr",
    name: "OCR PDF",
    short: "Make searchable",
    description: "OCR scanned PDFs in-browser (Tesseract) → searchable PDF with Hindi/English languages.",
    category: "ai",
    icon: ScanText,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "summarize",
    href: "/summarize",
    name: "Summarize PDF",
    short: "Extract & outline",
    description: "Extract text and generate a simple local outline/summary.",
    category: "ai",
    icon: Sparkles,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "translate",
    href: "/translate",
    name: "Translate PDF",
    short: "Free local / browser",
    description: "Extract text → browser Translator API or offline glossary mode. No paid MT.",
    category: "ai",
    icon: Languages,
    accept: "application/pdf",
    status: "partial",
  },
  {
    slug: "chat-pdf",
    href: "/chat-pdf",
    name: "Ask PDF",
    short: "Extractive Q&A",
    description: "Free extractive Q&A: keyword/sentence ranking — no paid LLM.",
    category: "ai",
    icon: MessageSquare,
    accept: "application/pdf",
    featured: true,
  },

  // —— View ——
  {
    slug: "pdf-reader",
    href: "/pdf-reader",
    name: "PDF reader",
    short: "Lightweight viewer",
    description: "Open and flip through a PDF privately in your browser.",
    category: "view",
    icon: BookOpenCheck,
    accept: "application/pdf",
  },

  // —— Batch ——
  {
    slug: "batch",
    href: "/batch",
    name: "Batch workspace",
    short: "Multi-file queue",
    description:
      "Drop many PDFs, pick one local operation (compress, OCR, unlock, watermark, and more), then download a ZIP. 100% in-browser.",
    category: "batch",
    icon: FolderKanban,
    featured: true,
    accept: "application/pdf",
    multiple: true,
  },

  {
    slug: "pdf-info",
    href: "/pdf-info",
    name: "PDF info / word count",
    short: "Pages · words · meta",
    description: "Page count, word count, file size, and document metadata.",
    category: "view",
    icon: Calculator,
    accept: "application/pdf",
  },
];

export function getTool(slug: string) {
  return TOOLS.find((t) => t.slug === slug);
}

export function toolsByCategory(cat: ToolCategory) {
  return TOOLS.filter((t) => t.category === cat);
}

export function featuredTools() {
  return TOOLS.filter((t) => t.featured);
}

export function relatedTools(slug: string, limit = 4) {
  const tool = getTool(slug);
  if (!tool) return TOOLS.filter((t) => t.slug !== slug).slice(0, limit);
  return TOOLS.filter(
    (t) => t.slug !== slug && t.category === tool.category
  )
    .concat(TOOLS.filter((t) => t.slug !== slug && t.featured))
    .filter((t, i, arr) => arr.findIndex((x) => x.slug === t.slug) === i)
    .slice(0, limit);
}
